export const COMMERCIAL_COLOR_SWATCHES = [
  "#ffffff", "#0f172a", "#64748b", "#94a3b8", "#1e3a8a",
  "#2563eb", "#0891b2", "#dc2626", "#7c2d12", "#16a34a",
  "#166534", "#ca8a04", "#facc15", "#ea580c", "#7c3aed",
];

export const COMMERCIAL_VEHICLE_TYPE_OPTIONS = [
  "Ambulance",
  "Bus",
  "Cargo Van",
  "Car Carrier",
  "Car Transporter",
  "Chassis Cab",
  "Container Truck",
  "Crew Bus",
  "Delivery Van",
  "Flatbed Truck",
  "Food Truck",
  "Mini Bus",
  "Mini Truck",
  "Panel Van",
  "Pickup Truck",
  "Prime Mover",
  "Refrigerated Truck",
  "Recovery Truck",
  "School Bus",
  "Water Tanker Truck",
];

export const commercialFormConfig = {
  key: "COMMERCIAL",
  label: "Commercial Vehicles",

  vehicleInfoFields: [
    { name: "title", label: "Vehicle Title", type: "text", required: true, span: 2, placeholder: "e.g. 2023 Mercedes-Benz Arocs 5460 Tipper Truck" },
    { name: "brand", label: "Brand", type: "brandSelect", required: true },
    { name: "catalogModel", label: "Model", type: "modelSelect", required: true },
    { name: "variantTrim", label: "Variant / Trim", type: "variantSelect" },
    { name: "vehicleType", label: "Vehicle Type", type: "select", required: true, options: COMMERCIAL_VEHICLE_TYPE_OPTIONS },
    { name: "manufacturingYear", label: "Manufacturing Year", type: "yearSelect", required: true },
    { name: "sellerName", label: "Seller Name", type: "text", required: true, placeholder: "e.g. Fleet Motors Bahrain" },
    { name: "bodyType", label: "Body Type", type: "select", required: true },
    { name: "mileage", label: "Mileage", type: "number", required: true, placeholder: "e.g. 42500" },
    { name: "fuelType", label: "Fuel Type", type: "select", required: true, options: ["Diesel", "Petrol", "Electric", "Hybrid", "CNG", "LNG"] },
    { name: "transmission", label: "Transmission", type: "select", required: true, options: ["Manual", "Automatic", "Automated Manual (AMT)", "Semi-Automatic"] },
    { name: "exteriorColor", label: "Exterior Color", type: "colorSwatch", swatches: COMMERCIAL_COLOR_SWATCHES, span: 2 },
    { name: "vinNumber", label: "VIN Number", type: "vin", span: 2 },
    { name: "registrationExpiry", label: "Registration Expiry", type: "date" },
    { name: "registrationCountry", label: "Registration Country", type: "countrySelect", required: true },
    { name: "companyName", label: "Company Name", type: "text", placeholder: "e.g. Fleet Motors Bahrain", dealerOnly: true },
    { name: "mobileNumber", label: "Mobile Number", type: "phone", required: true, placeholder: "7767754397" },
    { name: "whatsappNumber", label: "WhatsApp Number", type: "phone", required: true, placeholder: "7767754397" },
    { name: "whatsappAvailable", label: "WhatsApp available on mobile number", type: "toggleSwitch", fullWidth: true, description: "Turn on to use the same mobile number for WhatsApp." },
    { name: "contactEmail", label: "Contact Email Address", type: "email", required: true, placeholder: "e.g. seller@example.com" },
    { name: "description", label: "Vehicle Description", type: "textarea", required: true, span: 2, placeholder: "Describe the vehicle's condition, usage history, and standout features..." },
    { name: "hasLoanOption", label: "Financing Available", description: "Is financing available for this vehicle?", type: "toggleSwitch", span: 2 },
  ],

  specsFields: [
    { name: "driveConfiguration", label: "Drive Type", type: "select", options: ["4x2", "4x4", "6x2", "6x4", "6x6", "8x4", "8x6", "8x8"] },
    { name: "enginePower", label: "Engine Power", type: "text", placeholder: "e.g. 510 HP" },
    { name: "torque", label: "Torque", type: "text", placeholder: "e.g. 1800 Nm" },
    { name: "emissionStandard", label: "Emission Standard", type: "select", options: ["Euro 3", "Euro 4", "Euro 5", "Euro 6"] },
    { name: "payloadCapacity", label: "Payload Capacity", type: "text", placeholder: "e.g. 18,500 kg" },
    { name: "grossVehicleWeight", label: "Gross Vehicle Weight (kg)", type: "text", placeholder: "e.g. 26,000 kg" },
    { name: "fuelTankCapacity", label: "Fuel Tank Capacity", type: "text", placeholder: "e.g. 300 L" },
    { name: "seatingCapacity", label: "Seating Capacity", type: "number", placeholder: "e.g. 3" },
    { name: "doorCount", label: "Door Count", type: "number", placeholder: "e.g. 2" },
    { name: "towingCapacity", label: "Towing Capacity (kg)", type: "number", placeholder: "e.g. 3500" },
    { name: "wheelbase", label: "Wheelbase (mm)", type: "number", placeholder: "e.g. 3600" },
    { name: "overallLength", label: "Overall Length (mm)", type: "number", placeholder: "e.g. 7200" },
    { name: "overallWidth", label: "Overall Width (mm)", type: "number", placeholder: "e.g. 2400" },
    { name: "overallHeight", label: "Overall Height (mm)", type: "number", placeholder: "e.g. 3100" },
    { name: "previousOwners", label: "Number of Owners", type: "select", options: ["single", "multiple"] },
    { name: "warranty", label: "Warranty", type: "select", options: ["Manufacturer", "Dealer", "Extended", "None"] },
    { name: "serviceHistory", label: "Service History", type: "select", options: ["Full", "Partial", "None"] },
    { name: "accidentHistory", label: "Accident History", type: "select", options: ["No Accident", "Minor", "Major"] },
    { name: "insuranceValid", label: "Insurance Covered", type: "toggleSwitch", fullWidth: true },
    { name: "numberOfKeys", label: "Number of Keys", type: "select", options: ["1", "2", "3+"] },
  ],

  featureGroups: [
    { key: "features", label: "Features", options: ["360 Camera", "ABS (Anti-lock Braking System)", "Adaptive Cruise Control", "Adjustable Air Suspension", "Adjustable Driver Seat", "Air Conditioning", "Air Suspension Seat", "Airbags", "Alarm System", "Android Auto", "Apple CarPlay", "Automatic Climate Control", "Blind Spot Monitoring", "Bluetooth Connectivity", "Cargo Partition", "Central Locking", "Cruise Control", "Dash Camera", "Daytime Running Lights (DRL)", "Differential Lock", "Digital Instrument Cluster", "Driver Fatigue Alert", "Dual Airbags", "Electric Mirrors", "Electric Parking Brake", "Electric Windows", "Emergency Brake Assist", "Engine Brake", "Fire Extinguisher", "Fog Lights", "Forward Collision Warning", "GPS Navigation", "Hands-Free Calling", "Heated Mirrors", "Hill Start Assist", "Hydraulic Liftgate", "Keyless Entry", "Lane Departure Warning", "LED Headlights", "LED Tail Lights", "Load Securing Hooks", "Mobile App Connectivity", "Multi-Function Steering Wheel", "Parking Sensors", "Power Steering", "Power Tail Lift", "PTO (Power Take-Off)", "Push Button Start", "Rear Air Conditioning", "Rear Camera", "Remote Central Locking", "Roof Rack", "Side Steps", "Sleeper Cabin", "Smart Key", "Spare Wheel", "Speed Limiter", "Stability Control", "Start/Stop System", "Sun Visor", "Suspension Seat", "Touchscreen Display", "Traction Control", "Trailer Brake System", "Trailer Hitch", "Tyre Pressure Monitoring System (TPMS)", "USB Charging Port", "Walkthrough Cab", "Wheel Covers", "Wireless Phone Charging"] },
  ],
};
